CREATE TABLE forecasts (
    forecastID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    recommendation TEXT,
    recommendationFor TIMESTAMP WITH TIME ZONE,
    createdAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
);